const header=document.querySelector('#header'),menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav'),heroMedia=document.querySelector('.hero-media'),immersive=document.querySelector('.immersive-bg');
addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>40);if(immersive){const r=immersive.parentElement.getBoundingClientRect();immersive.style.transform=`translateY(${r.top*.035}px)`}} ,{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
if(matchMedia('(pointer:fine)').matches){document.querySelector('.hero').addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*12,y=(e.clientY/innerHeight-.5)*8;heroMedia.style.transform=`translate(${x}px,${y}px) scale(1.035)`});addEventListener('mousemove',e=>{document.querySelector('.cursor-glow').style.left=e.clientX+'px';document.querySelector('.cursor-glow').style.top=e.clientY+'px'})}
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const countObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.count,start=performance.now();function tick(now){const p=Math.min((now-start)/1300,1);el.textContent=Math.floor(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObserver.unobserve(el)}),{threshold:.7});document.querySelectorAll('[data-count]').forEach(el=>countObserver.observe(el));
const toast=document.querySelector('.toast');function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
document.querySelector('#property-search').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#imoveis').scrollIntoView({behavior:'smooth'});notify('A mostrar a nossa seleção de imóveis.')});
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();notify('Obrigado. O seu pedido foi registado.');e.target.reset()});
document.querySelectorAll('.card-image button').forEach(btn=>btn.addEventListener('click',()=>{btn.textContent=btn.textContent==='♡'?'♥':'♡';notify(btn.textContent==='♥'?'Adicionado aos favoritos.':'Removido dos favoritos.')}));
